Feature/01 items manage migrations
Apro-yuto/highlight pull request #30
Opened 2022-01-10 17:30 UTC by masato5579

@YutaManaka @Apro-yuto 

間中さん、長島さん、
トップページのマイグレーションファイルを作成しました。

ご確認のほど、よろしくお願いします。

2022-01-13 16:41 UTC, masato5579 commented
@Apro-yuto 
仕様変更後のmigrationファイルの修正が完了しました。
ご確認のほど、よろしくお願いいたします。

2022-01-14 23:26 UTC, Apro-yuto requested changes
レビューしました。
修正お願いします！

2022-01-15 14:13 UTC, masato5579 commented
@Apro-yuto 
ご指摘いただいた点、全て修正いたしました。
また、.php-cs-fixer.cacheをリモートから削除しました。

相談ですが、
ユーザーが任意で変えられないテーブル（color,color_item,statusesテーブル）などは
create_at,update_atカラムは必要ないと思うのですがどうでしょう？

2022-01-16 01:39 UTC, Apro-yuto commented
@masato5579 
update_atカラムを使用する可能性があると思ったけど、よく考えたらマイグレーションファイルで確認できるからいいや
消しちゃってー！

2022-01-16 14:21 UTC, masato5579 commented
@Apro-yuto 

color, statusesテーブルのcreated_at,update_atカラムを削除しました。
ご確認のほど、よろしくお願いいたします。

2022-01-18 15:30 UTC, merged