Feature/01 items manage model
Apro-yuto/highlight pull request #31
Opened 2022-01-12 16:34 UTC by masato5579

@YutaManaka @Apro-yuto 

Topのモデルの作成が完了しました。
ご確認のほど、よろしくお願いたします

2022-01-14 13:29 UTC, masato5579 commented
@Apro-yuto 
仕様変更箇所のModelの変更も完了しましたので、
ご確認よろしくお願いいたします。

2022-01-16 02:28 UTC, Apro-yuto requested changes

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Category.php
> +        'user_id',
commentない

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Category.php
> +        'comment',
理由なければいらない

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Color.php
> +        'name',
$fillableはだあ移入可能な値なのでこのメンバ変数ごと必要ないかと思います！

逆に代入が『必要ない』ため$guardedメンバ変数が必要かも
https://readouble.com/laravel/5.2/ja/eloquent.html#mass-assignment

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Color.php
> +        'comment',
理由なければいらない

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Item.php
> +        'created_at',
いらないよ

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Item.php
> +        'updated_at',
いらないよ

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Shop.php
> +        'user_id',
comment

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Shop.php
> +        'comment',
理由なければいらない

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Status.php
> +    protected $fillable = [
代入可能ではない必要があるため、この変数はいりません

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Supplier.php
> +        'user_id',
comment

2022-01-16 02:28 UTC, Apro-yuto commented on app/Models/Supplier.php
> +        'comment',
理由なければいらない

2022-01-16 15:03 UTC, masato5579 commented
@Apro-yuto 
ご指摘いただいた点修正致しましたので、
ご確認のほど、よろしくお願いいたします。

2022-01-18 15:38 UTC, merged