ヘッダーコンポーネント作成　#28
Apro-yuto/highlight pull request #32
Opened 2022-01-13 18:10 UTC by Apro-yuto

2022-01-15 15:43 UTC, masato5579 commented
@Apro-yuto 
headerの「Highlight」のタイトルですが、
左端に配置されていますが、XDのデザインだと中央寄せになっています。
こちらこのままで大丈夫でしょうか？

2022-01-15 15:45 UTC, masato5579 commented
@Apro-yuto 
ちょっと実装とは関係ないですが、
UserのSeederがコメントアウトになっているので、
コメントインした方が実装者やレビュワーが確認しやすいと思います。

2022-01-16 02:30 UTC, Apro-yuto commented
@masato5579 XDはデザインではなく、ワイヤーフレームとか画面設計の立ち位置だと思います

`UserのSeederがコメントアウトになっているので、`
↑？？？？

2022-01-16 02:43 UTC, masato5579 requested changes

2022-01-16 04:02 UTC, merged