とりあえず、Seederwo
Apro-yuto/highlight pull request #44
Opened 2022-01-22 19:20 UTC by masato5579

2022-01-22 19:24 UTC, Apro-yuto commented
@masato5579 ありがとう！マージ先だけdevelopから変更お願いします、、、

2022-01-25 14:26 UTC, YutaManaka commented on database/seeders/LableSeeder.php
> +           ]);
@masato5579 ラベルを持たないアイテム、ラベルを1つ持つアイテム、ラベルを2つ持つアイテム、ラベルを3つ持つアイテム...のようなものを想定して作ってみてはどうでしょう？

2022-01-25 14:27 UTC, YutaManaka commented
@masato5579 とりいそぎ、確認してみました。
userテーブルにseeder以外のデータがあった場合、下記を考慮したほうがよいかもです。
(userがid=1のものしかなければ問題ないので無視してください。)

BrandSeederとItemSeederでそれぞれランダムなuser_idを付与してますが、大丈夫ですか？
リレーションしてるブランドとアイテムで別のuserにリレーションしいるものも出てきてしまいます。(添付画像参照)
![brands](https://user-images.githubusercontent.com/54618797/150991045-deabb62f-fff4-4b8e-b962-a310455b29f7.png)
![items](https://user-images.githubusercontent.com/54618797/150991063-5403e175-9f02-4112-873d-272fb43dd4a5.png)

他のテーブル(Categories,Shops,Suppliers)も、リレーションがある部分のuser_idやitem_idをランダムに付与はまずいのでは。
全てfactoryでランダムに作るのではなく、リレーションを想定してみてはいかがでしょう？

2022-01-26 13:14 UTC, masato5579 commented on database/factories/ItemFactory.php
>              'selling_price'  => mt_rand(0, 1000000),
@YutaManaka 
そうですね。。。
brandテーブルとshopテーブルとsupplierテーブルにitem_idを持っているので、
もしかしたら、これらのid自体いらないような気がするので、
会議で相談します。

2022-01-26 13:18 UTC, masato5579 commented
@YutaManaka 

> @masato5579 とりいそぎ、確認してみました。
userテーブルにseeder以外のデータがあった場合、下記を考慮したほうがよいかもです。
(userがid=1のものしかなければ問題ないので無視してください。)
BrandSeederとItemSeederでそれぞれランダムなuser_idを付与してますが、大丈夫ですか？
リレーションしてるブランドとアイテムで別のuserにリレーションしいるものも出てきてしまいます。(添付画像参照)

こちらに関しては、その通りですね。
user_idを「1」だけを想定して、作り直します。

2022-01-27 14:08 UTC, masato5579 commented
@Apro-yuto @YutaManaka 

本件、修正しましたので、ご確認のほどよろしくお願いいたします。
## 修正した点
- itemsテーブルのbrand・shop・supplierカラムの削除（それぞれのテーブルにitem_idを持っているため）
- itemsテーブル変更に伴うModelとFactoryの削除
- Seederの作成

## Seederの内容
前提：userは一人しかいない想定
- BaseTemplateSeeder→user_id：1で指定
- Brand・Category・Lable・Shop・SupplierSeeder → item_idも指定・item_idに対してひとつしか作れない
理由：itemに対して1つしか紐づけられないため
ダブってSeedした場合、警告を出すように実装

- ItemSeeder  → いくつでも作成できるように
- LableSeeder → item_idを指定・item_idに対していくつでも作れる
理由：itemに対していくつでも紐づけられるため

## 運用方法
1. 一旦、全体でseed (run artisan db:seed )
2. 必要な時に必要な分だけ、Seedする（Wiki作ります。）

2022-01-27 15:04 UTC, YutaManaka reviewed
@masato5579 指摘箇所多いですが、内容はほぼ一緒です。  
ご確認ください。

2022-01-27 15:04 UTC, YutaManaka commented on database/seeders/LableSeeder.php
> +        $itemId = 1;
@masato5579 BrandSeederと同じ。  
また、[このコメント](https://github.com/Apro-yuto/highlight/pull/44#discussion_r791766368)の想定にはなってないですね...。
$itemId = 1の商品はラベルなし
$itemId = 2の商品はラベル1個
$itemId = 3の商品はラベル2個
$itemId = 4の商品はラベル3個

みたいだといい感じかと思いました。

2022-01-27 15:04 UTC, YutaManaka commented on database/seeders/ShopSeeder.php
> +        $itemId = 1;
@masato5579 BrandSeederと同じ。

2022-01-27 15:04 UTC, YutaManaka commented on database/seeders/SupplierSeeder.php
> +        $itemId = 1;
@masato5579 BrandSeederと同じ。

2022-01-27 15:44 UTC, masato5579 commented
@YutaManaka 
ご丁寧にご指摘ありがとうございます。

 修正しましたので、ご確認のほどよろしくお願いいたします。

2022-01-29 19:10 UTC, masato5579 commented
@Apro-yuto @YutaManaka 

shop/supplier/category/brandテーブルにあったitem_idを削除しました。
使用ではitem_idを持っていたのですが、
これがあるとSeederを作る際かなり面倒・別に必要ではないという理由から削除しました。

その際に対象のmigration / model / factory / seederを修正しました。
右往左往して大変申し訳ないです。

ご確認のほどよろしくお願いいたします。

2022-01-30 08:47 UTC, YutaManaka reviewed
@masato5579 粘り強い修正、ありがとうございます！
最後1点だけ、気になる点があったので、その修正が終われば自分はOKだと思います！

2022-01-30 08:47 UTC, YutaManaka commented on database/seeders/LableSeeder.php
> +                'item_id' => $i,
```suggestion
        $itemCounts = 10;

        for ($i = 0; $i < $itemCounts; ++$i) {
            Lable::factory($i)->create([
                'item_id' => $i + 1,
```

ラベルを多めに配置した商品も作っておいた方が、フロント実装する時に役立つと思うので、いかがでしょうか？
(ラベルが多い場合、スクロールを実装する、と聞いたので。)
item_id=1→ラベル0個
item_id=2→ラベル1個
item_id=3→ラベル2個
...
item_id=10→ラベル9個

2022-01-30 10:17 UTC, Apro-yuto requested changes
ざっとレビューしましたが、正直何度も練ってくれたので指摘箇所そんなにないですw
お願いしますー。

2022-01-30 10:17 UTC, Apro-yuto commented on database/factories/SupplierFactory.php
> +            'user_id' => 1,
BaseTemplateのファクトリには、user_id => User::factory()と記述があります。

シーダー側でオーバーライドするのであれば、どちらでもいいと思うのでどちらかに合わせて下さい。

2022-01-30 10:17 UTC, Apro-yuto commented on database/seeders/ItemSeeder.php
> +                'user_id'     => 1,
ItemFactoryでは、user_id => 1 と指定されてるのでこの記述は不要かと思います。
```suggestion

```

2022-01-30 10:17 UTC, Apro-yuto commented on database/seeders/ShopSeeder.php
> +            'user_id' => 1,
ShopFactoryでは、user_id => 1 と指定されてるのでこの記述は不要かと思います。
```suggestion
        Shop::factory(10)->create();
```

2022-01-30 10:17 UTC, Apro-yuto commented on database/seeders/SupplierSeeder.php
> +            'user_id' => 1,
SupplierFactoryでは、user_id => 1 と指定されてるのでこの記述は不要かと思います。
```suggestion
        Supplier::factory(10)->create();
```

2022-01-30 14:53 UTC, masato5579 commented
@Apro-yuto @YutaManaka 

お忙しい中、レビューいただきありがとうございました。
修正しましたので、ご確認お願いします。

OKでしたら、マージお願いします。

2022-01-31 11:07 UTC, YutaManaka commented
@masato5579 粘り強い修正おつかれさまでした。自分は指摘なしです。
@Apro-yuto 問題なければマージお願いします！

2022-01-31 13:27 UTC, merged