商品詳細ページを作成しました。
Apro-yuto/highlight pull request #52
Opened 2022-02-06 10:56 UTC by masato5579

@Apro-yuto @hiromichi-hayashi @YutaManaka 

内容
バックエンドの処理ができてないので、とりあえず、
見た目と簡単なuseStateの処理だけ書きました。

ラベルの追加・編集機能や、ベーステンプレートのウィジウィグの実装などはやってません。
別ブランチにします。

とりあえず、コードの書き方めちゃくちゃかもしれないので、
厳しめにレビューください。

2022-02-07 13:27 UTC, YutaManaka reviewed
@masato5579 reactのコードほぼ初見なので、大した指摘はできてないと思いますが...。  
ご確認お願いします！

2022-02-07 13:27 UTC, YutaManaka commented on resources/js/components/LabelInput.tsx
> +      lg={3}
```suggestion
      mt={4}
      lg={4}
```
@masato5579 PCだとだいぶ窮屈にみえます。  
特にラベル名が全角3文字で見切れるのは実用的ではない気がします。
3つずつ並べる/文字を小さくする/要素の間の余白を大きくする などの工夫が必要かと。

2022-02-07 13:27 UTC, YutaManaka commented on resources/js/Pages/Item/Detail.tsx
> +                handleChange={handleStatusChange}
```suggestion
                onChange={HandleStatusChange}
```
@masato5579 ここは要議論ですが...イベントハンドラの命名ルールは色々ありますが、[ドキュメント](https://ja.reactjs.org/docs/handling-events.html)によると上記が推奨されてるみたいですね。  

ちなみに、ゴルフ案件(vue3)では

```
onChanged={onStatusChanged}
```
みたいな書き方してました。

どれがいいですかね？

2022-02-07 14:42 UTC, masato5579 commented on resources/js/Pages/Item/Detail.tsx
> +                handleChange={handleStatusChange}
@YutaManaka 

onChangeが無難だったので、直します！

2022-02-08 10:01 UTC, Apro-yuto commented
![スクリーンショット 2022-02-08 18 34 50](https://user-images.githubusercontent.com/84962399/152959023-c6915a43-52ca-4e99-8178-aed71ee07177.png)
全体を見て、画像がデカすぎると思いますがどうですかね？？
少し画像のエリアを狭くしたらいい感じかも！

![スクリーンショット 2022-02-08 18 36 22](https://user-images.githubusercontent.com/84962399/152959290-666b321c-c8b3-427e-83bb-dd065eeebaef.png)

2022-02-08 10:19 UTC, Apro-yuto commented
![スクリーンショット 2022-02-08 19 17 55](https://user-images.githubusercontent.com/84962399/152967249-1aa07a1a-22b3-489a-823b-84dca6df52a3.png)

ここの「 円 」だけplaceholderから外せませんか？

2022-02-08 10:23 UTC, Apro-yuto commented
![スクリーンショット 2022-02-08 19 22 48](https://user-images.githubusercontent.com/84962399/152968017-9505e569-f0dc-422b-9a32-0116a753e5a9.png)
ここの「＋」の周りの円消してもいいかも

2022-02-08 10:26 UTC, Apro-yuto commented
![スクリーンショット 2022-02-08 19 25 21](https://user-images.githubusercontent.com/84962399/152968546-63bfcc54-1cd3-4000-be58-19176a506df4.png)

ラベルのUIはこういうUIにして欲しいなあ、、、

2022-02-08 10:29 UTC, Apro-yuto commented
@masato5579 
![スクリーンショット 2022-02-08 19 28 51](https://user-images.githubusercontent.com/84962399/152969165-b6ec39cb-778d-49c9-a690-4c760c80b7e2.png)

ステータスの上に少し余白が欲しい！

2022-02-08 10:53 UTC, Apro-yuto commented
@masato5579 
全体的にフォントを見直した方がいいかもー
もう少しフォントサイズ大きくしてみたり、小さくしてみたり、色の濃さを薄くしてみたり試行錯誤してみてー

2022-02-08 10:55 UTC, Apro-yuto commented
@masato5579 
![スクリーンショット 2022-02-08 19 52 23](https://user-images.githubusercontent.com/84962399/152973201-2fca4903-3534-4026-92aa-2736e1614aac.png)
![スクリーンショット 2022-02-08 19 52 30](https://user-images.githubusercontent.com/84962399/152973207-3b0aa17f-76ee-4866-a9a0-b2d5afb30ed9.png)

ここはモーダルが出るフックとなるので、下矢印を消してモーダルがでそうなUIに変えて下さい！

2022-02-08 10:56 UTC, Apro-yuto commented
@masato5579 
![スクリーンショット 2022-02-08 19 56 12](https://user-images.githubusercontent.com/84962399/152973569-06053745-1189-4662-93c7-99fa9cb89a76.png)
ステータスはインプット含めて一行の方がユーザーが操作しやすいかも

2022-02-08 10:58 UTC, Apro-yuto commented
@masato5579 
![スクリーンショット 2022-02-08 19 57 07](https://user-images.githubusercontent.com/84962399/152973725-357b0104-9881-416f-bb3b-552f6ff077ea.png)

商品名をもうちょっと目立たせてもいいかも。

2022-02-08 11:00 UTC, Apro-yuto commented
@masato5579 
全体的に「仕入れ値」→「仕入値」じゃなかったっけ？

2022-02-08 18:06 UTC, Apro-yuto requested changes
@masato5579 @YutaManaka 
ざっとUIのレビューとコードのレビューをしました。
まだまだあると思うんですが、一旦間中さん分と一緒に指摘箇所を直して下さい

2022-02-08 18:06 UTC, Apro-yuto commented on routes/web.php
> +            return Inertia::render('Item/Detail', ['id' => $item_id]);
@masato5579 
このタイミングで、バックエンドでモックを作成して、フロントで表示するって言う形にしてもいいかも

今回はやらなくてもいいや

2022-02-08 18:06 UTC, Apro-yuto commented on routes/web.php
> +            return Inertia::render('Item/Detail', ['id' => $item_id]);
メモメモ

2022-02-08 18:06 UTC, Apro-yuto commented on routes/web.php
> +            return Inertia::render('Item/Detail', ['id' => $item_id]);
@Apro-yuto

2022-02-08 18:06 UTC, Apro-yuto commented on resources/js/components/TextInput.tsx
> +import React from 'react'
@masato5579 
Priceinputと一緒にできそうなのでしてほしい

2022-02-08 19:33 UTC, Apro-yuto commented
@masato5579 
![スクリーンショット 2022-02-08 18 34 50](https://user-images.githubusercontent.com/84962399/152959023-c6915a43-52ca-4e99-8178-aed71ee07177.png)

あとここの画像複数枚入ってもいいようなUIにして欲しいです！！

2022-02-10 16:05 UTC, Apro-yuto commented on resources/js/Pages/Item/Detail.tsx
> +          <Typography
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

2022-02-11 12:43 UTC, masato5579 commented on resources/js/components/LabelFormDialog.tsx
> +import React from 'react'
スタイル調整大変なので、できるかもですが、一旦見送りで。
別issueに立てます。

2022-02-11 13:17 UTC, masato5579 commented on resources/js/components/TextInput.tsx
> +import React from 'react'
@Apro-yuto 

PriceInputとTextInputのPropsの受け取る型を
stringとnumberを許容すれば、多分大丈夫なんですが、
それだと、typeScriptを使ってる意味がない気がするので、
個人的には、分けていても良いと思うのですが、どうでしょう？（断じてめんどくさいわけではない。）

2022-02-12 06:00 UTC, masato5579 commented
下記以外は多分修正したので、
ご確認よろしくお願いいたします。

下記ちょっと難しかったので一緒にやんないですか？
https://github.com/Apro-yuto/highlight/pull/52#issuecomment-1032474271
https://github.com/Apro-yuto/highlight/pull/52#issuecomment-1032478404
https://github.com/Apro-yuto/highlight/pull/52#discussion_r801913034

2022-02-17 14:06 UTC, Apro-yuto commented on app/Models/Item.php
> +        return $this->hasMany(Lable::class, 'item_id', 'id');
??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

2022-02-20 13:24 UTC, Apro-yuto requested changes

2022-02-20 13:24 UTC, Apro-yuto commented on resources/js/Pages/Item/Detail.tsx
> +        <Grid item xs={12} lg={6}>
@masato5579 
ここ変わった？

2022-02-20 13:24 UTC, Apro-yuto commented on resources/js/Pages/Item/Detail.tsx
> +        <Grid item xs={12} lg={6} sx={{ mt: { xs: 6, lg: 0 } }}>
@masato5579 
ここも変わってる？

2022-02-21 14:08 UTC, masato5579 commented on app/Models/Item.php
> +    public function itemImageUrls()
別ブランチ

2022-02-21 14:08 UTC, masato5579 commented on app/Models/Item.php
> +        return $this->hasMany(ItemImgUrl::class, 'item_id', 'id');
別ブランチ

2022-02-21 14:08 UTC, masato5579 commented on app/Models/ItemImgUrl.php
> +    protected $table = 'item_img_urls';
別ブランチ

2022-02-21 14:08 UTC, masato5579 commented on composer.json
> +    "doctrine/dbal": "^3.3",
別ブランチ

2022-02-22 17:00 UTC, Apro-yuto approved these changes

2022-02-22 17:04 UTC, merged